language: cpp

compiler:
  #- clang
  - gcc

addons:
  apt:
    packages:
    - gperf

sudo: false

notifications:
  email: false

os:
  # - linux
  - windows
  
install:
 - git clone https://github.com/steveicarus/ivtest.git
 #- gcc -v
 #- export PATH=$HOME/bin:$PATH
 
before_script:

  - which gcc
  - ls /c/tools/mingw64/bin
  - ls /c/tools/mingw64
  - ls /c/tools
  - ls /c
  #- gcc -v
 
  - PowerShell -Command "Invoke-WebRequest -outfile 7zsetup.exe http://www.7-zip.org/a/7z1604-x64.exe"
  - PowerShell -Command "Invoke-WebRequest -outfile msys2-x86_64-latest.tar.xz http://repo.msys2.org/distrib/msys2-x86_64-latest.tar.xz" 

  - PowerShell -Command "Start-Process .\7zsetup -ArgumentList '/S /D=c:/7zip' -Wait"
  - PowerShell -Command "C:\7zip\7z e msys2-x86_64-latest.tar.xz -Wait"
  - PowerShell -Command "C:\7zip\7z x msys2-x86_64-latest.tar -oC:\\" 

  - ls /c/
  - ls /c/msys64/usr/bin
  - ls /c/msys64
  - PowerShell -Command "C:\msys64\usr\bin\bash -lc 'pacman -Q'"
  - export PATH=/c/msys64/usr/bin:%PATH%
  - set
  - gcc -v
  - pacman-key --init
  #- bash -lc "pacman-key --init"
  #- PowerShell -Command "C:\msys64\usr\bin\pacman.exe -Q"
  - pacman -Q
  
  #- dir c:\
  #- dir c:\tools
  #- dir c:\tools\mingw64\bin
  
  - which gcc
  #- mingw-get install autoconf
  - autoconf
  - ./configure --prefix=$HOME

script:
  - make; make install
  - cd ivtest; perl vvp_reg.pl
