platform:
  - x64
environment:
  matrix:
    - MSYSTEM: MINGW64
install:
 - git clone https://github.com/steveicarus/ivtest.git
build_script:
  - C:\msys64\usr\bin\bash -lc "cd /c/projects/iverilog; exec 0</dev/null; ./autoconf.sh; ./configure; make; make install"
test_script: 
  - C:\msys64\usr\bin\bash -lc "cd /c/projects/iverilog/ivtest; perl vvp_reg.pl"
